const TWEET_STREAMING_API = 'search/tweets';
const STATUS_FILTER_STREAMING_API = 'statuses/filter';
const TRENDS_STREAMING_API = 'trends/place';
const TRENDS_API_PATH = '/trends';
const TWEETS_COUNT = 15;
const TRENDS_COUNT = 10;
const TWEETS_FILTER_TEXT = '#coding';
const LANGAUGE = 'en';
const WOEID = '23424848';

module.exports = {STATUS_FILTER_STREAMING_API,TWEET_STREAMING_API, TRENDS_STREAMING_API,TRENDS_API_PATH, TWEETS_FILTER_TEXT, TRENDS_COUNT, TWEETS_COUNT, LANGAUGE, WOEID}
